name: CI/CD Pipeline for Docker to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}        # Your AWS Access Key ID
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Your AWS Secret Access Key
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}          # Your AWS Session Token (if applicable)
          AWS_REGION: us-east-1             
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t assignment1 .

      - name: Tag the Docker image
        run: |
          echo "ECR Registry: ${{ secrets.ECR_REGISTRY }}"  # Add this line
          docker tag assignment1:latest ${{ secrets.ECR_REGISTRY }}:latest

      - name: Push the Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/assignment1:latest
