name: CI/CD for Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t your-image-name .

      - name: Tag Docker Image
        run: |
          docker tag your-image-name:latest 793896776375.dkr.ecr.us-east-1.amazonaws.com/clo835-week3:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 793896776375.dkr.ecr.us-east-1.amazonaws.com/clo835-week3:latest
